apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fau9nm222-go 
  janus-idp.io/tekton: fau9nm222-go
  backstage.io/kubernetes-id: fau9nm222-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fau9nm222-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  