apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fau9nm222-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fau9nm222-go 
  name: fau9nm222-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fau9nm222-go 
